version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-docker-nextjs-dev
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: pnpm dev
    ports:
      - "3000:3000"
